version: "3.8"

services:
  app:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=service
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/init.up.sql:/docker-entrypoint-initdb.d/init.up.sql
