logger:
  level: "local"
server:
  address: "localhost:8080"
  timeout: 4s
  iddle_timeout: 60s
  shutdown_timeout: 10s
db:
  host: "localhost"
  port: 5432
  username: "postgres"
  name: "service"
  password: "postgres"