name: github-ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.5'

    - name: Install dependencies
      run: go mod tidy

    - name: Build
      run: go build ./cmp/app/main.go

    - name: Test
      run: go test -coverprofile=coverage.txt ./...

    - name: Coverage by Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
